name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  IMAGE_NAME: e-commerce

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run Tests
        run: |
          chmod +x ./scripts/run-tests.sh
          ./scripts/run-tests.sh

  build:
    needs: test
    runs-on: ubuntu-20.04
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and Push Frontend
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -t ${REGISTRY}/${IMAGE_NAME}/frontend:latest ./frontend
            docker push ${REGISTRY}/${IMAGE_NAME}/frontend:latest
          else
            docker build -t ${REGISTRY}/${IMAGE_NAME}/frontend:develop ./frontend
            docker push ${REGISTRY}/${IMAGE_NAME}/frontend:develop
          fi
          
      - name: Build and Push Auth Service
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -t ${REGISTRY}/${IMAGE_NAME}/auth-service:latest ./services/auth-service
            docker push ${REGISTRY}/${IMAGE_NAME}/auth-service:latest
          else
            docker build -t ${REGISTRY}/${IMAGE_NAME}/auth-service:develop ./services/auth-service
            docker push ${REGISTRY}/${IMAGE_NAME}/auth-service:develop
          fi
          
      - name: Build and Push Product Service
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -t ${REGISTRY}/${IMAGE_NAME}/product-service:latest ./services/product-service
            docker push ${REGISTRY}/${IMAGE_NAME}/product-service:latest
          else
            docker build -t ${REGISTRY}/${IMAGE_NAME}/product-service:develop ./services/product-service
            docker push ${REGISTRY}/${IMAGE_NAME}/product-service:develop
          fi
          
      - name: Build and Push Order Service
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -t ${REGISTRY}/${IMAGE_NAME}/order-service:latest ./services/order-service
            docker push ${REGISTRY}/${IMAGE_NAME}/order-service:latest
          else
            docker build -t ${REGISTRY}/${IMAGE_NAME}/order-service:develop ./services/order-service
            docker push ${REGISTRY}/${IMAGE_NAME}/order-service:develop
          fi 