name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  IMAGE_NAME: e-commerce

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run Tests
        run: |
          chmod +x ./scripts/run-tests.sh
          ./scripts/run-tests.sh

  build:
    needs: test
    runs-on: ubuntu-20.04
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:latest
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:latest
          fi
          if [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:develop
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/frontend:develop
          fi
          
      - name: Build and Push Auth Service
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:${{ github.sha }} ./services/auth-service
          docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:${{ github.sha }}
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:latest
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:latest
          fi
          if [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:develop
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/auth-service:develop
          fi
          
      - name: Build and Push Product Service
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:${{ github.sha }} . 
          docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:${{ github.sha }}
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:latest
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:latest
          fi
          if [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:develop
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/product-service:develop
          fi
          
      - name: Build and Push Order Service
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:${{ github.sha }} ./services/order-service
          docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:${{ github.sha }}
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:latest
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:latest
          fi
          if [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            docker tag ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:develop
            docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}/order-service:develop
          fi 